### ISSUE TITLE
List count is displaying wrong number then the actual list count

### ISSUE THREAD

**Issue by dhanushkt** [dhanushkt/egross#10]
![issue](https://user-images.githubusercontent.com/34242050/88914215-eac9e180-d27f-11ea-963f-292f975d46c5.JPG)

**Comment by nithin356** [comment]
![image](https://user-images.githubusercontent.com/36884532/88916866-72195400-d284-11ea-81c8-7307f8a00c01.png)
i see no issue on my side may be for some user

**Comment by dhanushkt** [comment]
error is caused due to extra list which is generated during testing which had shop id as 0
