### ISSUE TITLE
Search doesn't redirect if there is no product id in URL

### ISSUE THREAD

**Issue by dhanushkt** [dhanushkt/egross#18]
![bug1](https://user-images.githubusercontent.com/34242050/89122525-624c7a80-d4e5-11ea-89f7-e2f0d194f783.JPG)

@Nikhil298  also remove the support box which is at the bottom of this image

**Comment by dhanushkt** [comment]
can redirect to **index.php** if there is no product id in URL

**Comment by nithin356** [comment]
Fixed
