### ISSUE TITLE
When u click on rice it's not displaying the item

### ISSUE THREAD

**Issue by Jnaneshballal** [dhanushkt/egross#21]
![15965358781541514816992549602259](https://user-images.githubusercontent.com/45487173/89282303-f5fa8400-d668-11ea-9375-164e708f46e7.jpg)

**Comment by dhanushkt** [comment]
@nithin356 check into this

**Comment by dhanushkt** [comment]
Duplicate of #22 

caused due to the same bug

**Comment by dhanushkt** [comment]
Caused due to the same bug as #22

**Comment by dhanushkt** [comment]
Duplicate of #22
