### ISSUE TITLE
When u click on chips there displaying rice

### ISSUE THREAD

**Issue by Jnaneshballal** [dhanushkt/egross#22]
![15965360434493489302414818488337](https://user-images.githubusercontent.com/45487173/89282563-58538480-d669-11ea-9e9d-64d02ad4c548.jpg)

**Comment by dhanushkt** [comment]
where did you click chips @Jnaneshballal  ?

**Comment by Jnaneshballal** [comment]
Rice is in snacks and beverages category it must come under cooking essentials

**Comment by dhanushkt** [comment]
![Annotation 2020-08-05 123605](https://user-images.githubusercontent.com/34242050/89382301-411fa000-d718-11ea-8062-06618c92be70.jpg)

 @nithin356  all of the subcategory has ID as 1 hence it is redirecting into wrong product page having scat ID

**Comment by dhanushkt** [comment]
the issue is in the **page view-category.php**
