### ISSUE TITLE
Add to list not not working as expected

### ISSUE THREAD

**Issue by nithin356** [dhanushkt/egross#26]
![Screenshot_2020-08-05-00-05-24-171_com android chrome](https://user-images.githubusercontent.com/36884532/89332094-6e386800-d6b0-11ea-85bc-2774c1ecb463.jpg)
Number of products which is added to the list of the same shop is generating multiple times it doesn't go into the same list but makes other list but while clicking on it the lost will be same.

**Comment by dhanushkt** [comment]
this issue is caused due to commit 0d07ac4
> list.pfp and header showing deleted list bug fixed
