### ISSUE TITLE
User side UI when we press view all inside product images are are not displaying

### ISSUE THREAD

**Issue by Jnaneshballal** [dhanushkt/egross#9]
![15960997708448046758771879448585](https://user-images.githubusercontent.com/45487173/88903586-928be300-d271-11ea-801c-93503be47e69.jpg)

**Comment by Jnaneshballal** [comment]
![15960998480087063019322031662686](https://user-images.githubusercontent.com/45487173/88903724-bfd89100-d271-11ea-96db-167208410202.jpg)

**Comment by nithin356** [comment]
no images are having in resource so there is a error so im closing the issue.

**Comment by dhanushkt** [comment]
javascript to handle this issue should be used, can't leave this issue as it is without solving
